// <auto-generated />
using Catalog.Persistence.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.Persistence.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250425182329_InicialCarritoProductosDB")]
    partial class InicialCarritoProductosDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Catalog")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Products", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = " Description for product 1",
                            Name = "Product1",
                            Price = 559m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = " Description for product 2",
                            Name = "Product2",
                            Price = 934m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = " Description for product 3",
                            Name = "Product3",
                            Price = 846m
                        },
                        new
                        {
                            ProductId = 4,
                            Description = " Description for product 4",
                            Name = "Product4",
                            Price = 587m
                        },
                        new
                        {
                            ProductId = 5,
                            Description = " Description for product 5",
                            Name = "Product5",
                            Price = 718m
                        },
                        new
                        {
                            ProductId = 6,
                            Description = " Description for product 6",
                            Name = "Product6",
                            Price = 985m
                        },
                        new
                        {
                            ProductId = 7,
                            Description = " Description for product 7",
                            Name = "Product7",
                            Price = 785m
                        },
                        new
                        {
                            ProductId = 8,
                            Description = " Description for product 8",
                            Name = "Product8",
                            Price = 242m
                        },
                        new
                        {
                            ProductId = 9,
                            Description = " Description for product 9",
                            Name = "Product9",
                            Price = 650m
                        },
                        new
                        {
                            ProductId = 10,
                            Description = " Description for product 10",
                            Name = "Product10",
                            Price = 979m
                        },
                        new
                        {
                            ProductId = 11,
                            Description = " Description for product 11",
                            Name = "Product11",
                            Price = 191m
                        },
                        new
                        {
                            ProductId = 12,
                            Description = " Description for product 12",
                            Name = "Product12",
                            Price = 973m
                        },
                        new
                        {
                            ProductId = 13,
                            Description = " Description for product 13",
                            Name = "Product13",
                            Price = 241m
                        },
                        new
                        {
                            ProductId = 14,
                            Description = " Description for product 14",
                            Name = "Product14",
                            Price = 956m
                        },
                        new
                        {
                            ProductId = 15,
                            Description = " Description for product 15",
                            Name = "Product15",
                            Price = 594m
                        },
                        new
                        {
                            ProductId = 16,
                            Description = " Description for product 16",
                            Name = "Product16",
                            Price = 494m
                        },
                        new
                        {
                            ProductId = 17,
                            Description = " Description for product 17",
                            Name = "Product17",
                            Price = 354m
                        },
                        new
                        {
                            ProductId = 18,
                            Description = " Description for product 18",
                            Name = "Product18",
                            Price = 508m
                        },
                        new
                        {
                            ProductId = 19,
                            Description = " Description for product 19",
                            Name = "Product19",
                            Price = 190m
                        },
                        new
                        {
                            ProductId = 20,
                            Description = " Description for product 20",
                            Name = "Product20",
                            Price = 176m
                        },
                        new
                        {
                            ProductId = 21,
                            Description = " Description for product 21",
                            Name = "Product21",
                            Price = 239m
                        },
                        new
                        {
                            ProductId = 22,
                            Description = " Description for product 22",
                            Name = "Product22",
                            Price = 901m
                        },
                        new
                        {
                            ProductId = 23,
                            Description = " Description for product 23",
                            Name = "Product23",
                            Price = 721m
                        },
                        new
                        {
                            ProductId = 24,
                            Description = " Description for product 24",
                            Name = "Product24",
                            Price = 731m
                        },
                        new
                        {
                            ProductId = 25,
                            Description = " Description for product 25",
                            Name = "Product25",
                            Price = 351m
                        },
                        new
                        {
                            ProductId = 26,
                            Description = " Description for product 26",
                            Name = "Product26",
                            Price = 233m
                        },
                        new
                        {
                            ProductId = 27,
                            Description = " Description for product 27",
                            Name = "Product27",
                            Price = 545m
                        },
                        new
                        {
                            ProductId = 28,
                            Description = " Description for product 28",
                            Name = "Product28",
                            Price = 60m
                        },
                        new
                        {
                            ProductId = 29,
                            Description = " Description for product 29",
                            Name = "Product29",
                            Price = 268m
                        },
                        new
                        {
                            ProductId = 30,
                            Description = " Description for product 30",
                            Name = "Product30",
                            Price = 541m
                        },
                        new
                        {
                            ProductId = 31,
                            Description = " Description for product 31",
                            Name = "Product31",
                            Price = 731m
                        },
                        new
                        {
                            ProductId = 32,
                            Description = " Description for product 32",
                            Name = "Product32",
                            Price = 121m
                        },
                        new
                        {
                            ProductId = 33,
                            Description = " Description for product 33",
                            Name = "Product33",
                            Price = 239m
                        },
                        new
                        {
                            ProductId = 34,
                            Description = " Description for product 34",
                            Name = "Product34",
                            Price = 324m
                        },
                        new
                        {
                            ProductId = 35,
                            Description = " Description for product 35",
                            Name = "Product35",
                            Price = 583m
                        },
                        new
                        {
                            ProductId = 36,
                            Description = " Description for product 36",
                            Name = "Product36",
                            Price = 520m
                        },
                        new
                        {
                            ProductId = 37,
                            Description = " Description for product 37",
                            Name = "Product37",
                            Price = 816m
                        },
                        new
                        {
                            ProductId = 38,
                            Description = " Description for product 38",
                            Name = "Product38",
                            Price = 418m
                        },
                        new
                        {
                            ProductId = 39,
                            Description = " Description for product 39",
                            Name = "Product39",
                            Price = 550m
                        },
                        new
                        {
                            ProductId = 40,
                            Description = " Description for product 40",
                            Name = "Product40",
                            Price = 777m
                        },
                        new
                        {
                            ProductId = 41,
                            Description = " Description for product 41",
                            Name = "Product41",
                            Price = 514m
                        },
                        new
                        {
                            ProductId = 42,
                            Description = " Description for product 42",
                            Name = "Product42",
                            Price = 478m
                        },
                        new
                        {
                            ProductId = 43,
                            Description = " Description for product 43",
                            Name = "Product43",
                            Price = 107m
                        },
                        new
                        {
                            ProductId = 44,
                            Description = " Description for product 44",
                            Name = "Product44",
                            Price = 605m
                        },
                        new
                        {
                            ProductId = 45,
                            Description = " Description for product 45",
                            Name = "Product45",
                            Price = 354m
                        },
                        new
                        {
                            ProductId = 46,
                            Description = " Description for product 46",
                            Name = "Product46",
                            Price = 703m
                        },
                        new
                        {
                            ProductId = 47,
                            Description = " Description for product 47",
                            Name = "Product47",
                            Price = 166m
                        },
                        new
                        {
                            ProductId = 48,
                            Description = " Description for product 48",
                            Name = "Product48",
                            Price = 840m
                        },
                        new
                        {
                            ProductId = 49,
                            Description = " Description for product 49",
                            Name = "Product49",
                            Price = 372m
                        },
                        new
                        {
                            ProductId = 50,
                            Description = " Description for product 50",
                            Name = "Product50",
                            Price = 517m
                        },
                        new
                        {
                            ProductId = 51,
                            Description = " Description for product 51",
                            Name = "Product51",
                            Price = 339m
                        },
                        new
                        {
                            ProductId = 52,
                            Description = " Description for product 52",
                            Name = "Product52",
                            Price = 782m
                        },
                        new
                        {
                            ProductId = 53,
                            Description = " Description for product 53",
                            Name = "Product53",
                            Price = 110m
                        },
                        new
                        {
                            ProductId = 54,
                            Description = " Description for product 54",
                            Name = "Product54",
                            Price = 928m
                        },
                        new
                        {
                            ProductId = 55,
                            Description = " Description for product 55",
                            Name = "Product55",
                            Price = 610m
                        },
                        new
                        {
                            ProductId = 56,
                            Description = " Description for product 56",
                            Name = "Product56",
                            Price = 667m
                        },
                        new
                        {
                            ProductId = 57,
                            Description = " Description for product 57",
                            Name = "Product57",
                            Price = 483m
                        },
                        new
                        {
                            ProductId = 58,
                            Description = " Description for product 58",
                            Name = "Product58",
                            Price = 644m
                        },
                        new
                        {
                            ProductId = 59,
                            Description = " Description for product 59",
                            Name = "Product59",
                            Price = 65m
                        },
                        new
                        {
                            ProductId = 60,
                            Description = " Description for product 60",
                            Name = "Product60",
                            Price = 614m
                        },
                        new
                        {
                            ProductId = 61,
                            Description = " Description for product 61",
                            Name = "Product61",
                            Price = 580m
                        },
                        new
                        {
                            ProductId = 62,
                            Description = " Description for product 62",
                            Name = "Product62",
                            Price = 91m
                        },
                        new
                        {
                            ProductId = 63,
                            Description = " Description for product 63",
                            Name = "Product63",
                            Price = 187m
                        },
                        new
                        {
                            ProductId = 64,
                            Description = " Description for product 64",
                            Name = "Product64",
                            Price = 350m
                        },
                        new
                        {
                            ProductId = 65,
                            Description = " Description for product 65",
                            Name = "Product65",
                            Price = 177m
                        },
                        new
                        {
                            ProductId = 66,
                            Description = " Description for product 66",
                            Name = "Product66",
                            Price = 526m
                        },
                        new
                        {
                            ProductId = 67,
                            Description = " Description for product 67",
                            Name = "Product67",
                            Price = 677m
                        },
                        new
                        {
                            ProductId = 68,
                            Description = " Description for product 68",
                            Name = "Product68",
                            Price = 972m
                        },
                        new
                        {
                            ProductId = 69,
                            Description = " Description for product 69",
                            Name = "Product69",
                            Price = 107m
                        },
                        new
                        {
                            ProductId = 70,
                            Description = " Description for product 70",
                            Name = "Product70",
                            Price = 789m
                        },
                        new
                        {
                            ProductId = 71,
                            Description = " Description for product 71",
                            Name = "Product71",
                            Price = 271m
                        },
                        new
                        {
                            ProductId = 72,
                            Description = " Description for product 72",
                            Name = "Product72",
                            Price = 636m
                        },
                        new
                        {
                            ProductId = 73,
                            Description = " Description for product 73",
                            Name = "Product73",
                            Price = 140m
                        },
                        new
                        {
                            ProductId = 74,
                            Description = " Description for product 74",
                            Name = "Product74",
                            Price = 397m
                        },
                        new
                        {
                            ProductId = 75,
                            Description = " Description for product 75",
                            Name = "Product75",
                            Price = 233m
                        },
                        new
                        {
                            ProductId = 76,
                            Description = " Description for product 76",
                            Name = "Product76",
                            Price = 837m
                        },
                        new
                        {
                            ProductId = 77,
                            Description = " Description for product 77",
                            Name = "Product77",
                            Price = 680m
                        },
                        new
                        {
                            ProductId = 78,
                            Description = " Description for product 78",
                            Name = "Product78",
                            Price = 568m
                        },
                        new
                        {
                            ProductId = 79,
                            Description = " Description for product 79",
                            Name = "Product79",
                            Price = 657m
                        },
                        new
                        {
                            ProductId = 80,
                            Description = " Description for product 80",
                            Name = "Product80",
                            Price = 246m
                        },
                        new
                        {
                            ProductId = 81,
                            Description = " Description for product 81",
                            Name = "Product81",
                            Price = 966m
                        },
                        new
                        {
                            ProductId = 82,
                            Description = " Description for product 82",
                            Name = "Product82",
                            Price = 581m
                        },
                        new
                        {
                            ProductId = 83,
                            Description = " Description for product 83",
                            Name = "Product83",
                            Price = 171m
                        },
                        new
                        {
                            ProductId = 84,
                            Description = " Description for product 84",
                            Name = "Product84",
                            Price = 321m
                        },
                        new
                        {
                            ProductId = 85,
                            Description = " Description for product 85",
                            Name = "Product85",
                            Price = 718m
                        },
                        new
                        {
                            ProductId = 86,
                            Description = " Description for product 86",
                            Name = "Product86",
                            Price = 472m
                        },
                        new
                        {
                            ProductId = 87,
                            Description = " Description for product 87",
                            Name = "Product87",
                            Price = 394m
                        },
                        new
                        {
                            ProductId = 88,
                            Description = " Description for product 88",
                            Name = "Product88",
                            Price = 390m
                        },
                        new
                        {
                            ProductId = 89,
                            Description = " Description for product 89",
                            Name = "Product89",
                            Price = 800m
                        },
                        new
                        {
                            ProductId = 90,
                            Description = " Description for product 90",
                            Name = "Product90",
                            Price = 495m
                        },
                        new
                        {
                            ProductId = 91,
                            Description = " Description for product 91",
                            Name = "Product91",
                            Price = 194m
                        },
                        new
                        {
                            ProductId = 92,
                            Description = " Description for product 92",
                            Name = "Product92",
                            Price = 117m
                        },
                        new
                        {
                            ProductId = 93,
                            Description = " Description for product 93",
                            Name = "Product93",
                            Price = 490m
                        },
                        new
                        {
                            ProductId = 94,
                            Description = " Description for product 94",
                            Name = "Product94",
                            Price = 498m
                        },
                        new
                        {
                            ProductId = 95,
                            Description = " Description for product 95",
                            Name = "Product95",
                            Price = 744m
                        },
                        new
                        {
                            ProductId = 96,
                            Description = " Description for product 96",
                            Name = "Product96",
                            Price = 163m
                        },
                        new
                        {
                            ProductId = 97,
                            Description = " Description for product 97",
                            Name = "Product97",
                            Price = 530m
                        },
                        new
                        {
                            ProductId = 98,
                            Description = " Description for product 98",
                            Name = "Product98",
                            Price = 602m
                        },
                        new
                        {
                            ProductId = 99,
                            Description = " Description for product 99",
                            Name = "Product99",
                            Price = 993m
                        },
                        new
                        {
                            ProductId = 100,
                            Description = " Description for product 100",
                            Name = "Product100",
                            Price = 191m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductInStockId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks", "Catalog");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 49
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 26
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 43
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 37
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 48
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 23
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 35
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 27
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 39
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 24
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 40
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 42
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 21
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 44
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 31
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 45
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 46
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 25
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 32
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 38
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 30
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 28
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 29
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 33
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 22
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 41
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Navigation("Stock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
